---
- name: Add MongoDB YUM Repository.
  yum_repository:
   name: MongoDB
   description: MongoDB YUM repository
   baseurl: https://repo.mongodb.org/yum/redhat/7/mongodb-org/3.6/x86_64/
   gpgkey: https://www.mongodb.org/static/pgp/server-3.6.asc
   gpgcheck: yes
- name: Install MongoDB.
  yum:
    name:
      - mongodb-org
    state: present
- name: Start MongoDB.
  service:
    name: mongod
    state: started
- name: Enable MongoDB.
  service:
    name: mongod
    enabled: yes
